var _cistrictNames = [
    { en : "yubei" , cn : "渝北"} ,
    { en : "yuzhong" , cn : "渝中"} ,
    { en : "wansheng" , cn : "万盛" } ,
    { en : "banan" , cn : "巴南"} ,
    { en : "changshou" , cn : "长寿"} ,
    { en : "fengdu" , cn : "丰都"} ,
    { en : "kaixian" , cn : "开县"} ,
    { en : "youyang" , cn : "酉阳"} ,
    { en : "qianjiang" , cn : "黔江"} ,
    { en : "fuling" , cn : "涪陵"} ,
    { en : "liangping" , cn : "梁平"} ,
    { en : "pengshui" , cn : "彭水"} ,
    { en : "zhongxian" , cn : "忠县"} ,
    { en : "wanzhou" , cn : "万州"} ,
    { en : "shizhu" , cn : "石柱"} ,
    { en : "dianjiang" , cn : "垫江"} ,
    { en : "rongchang" , cn : "荣昌"} ,
    { en : "nanchuan" , cn : "南川"} ,
    { en : "wulong" , cn : "武隆"} ,
    { en : "yunyang" , cn : "云阳"} ,
    { en : "wuxi" , cn : "巫溪"} ,
    { en : "hechuan" , cn : "合川"} ,
    { en : "dazu" , cn : "大足"} ,
    { en : "xiushan" , cn : "秀山"} ,
    { en : "fengjie" , cn : "奉节"} ,
    { en : "wushan" , cn : "巫山"} ,
    { en : "jiulongpo" , cn : "九龙坡" } ,
    { en : "shapingba" , cn : "沙坪坝" } ,
    { en : "tongliang" , cn : "铜梁" } ,
    { en : "tongnan" , cn : "潼南" } ,
    { en : "bishan" , cn : "璧山"} ,
    { en : "dadukou" , cn : "大渡口"} ,
    { en : "jiangjin" , cn : "江津" } ,
    { en : "yongchuan" , cn : "永川" } ,
    { en : "beibei" , cn : "北碚" } ,
    { en : "nanan" , cn : "南岸"} ,
    { en : "jiangbei" , cn : "江北"} ,
    { en : "qijiang" , cn : "綦江"} ,
    { en : "chengkou" , cn : "城口" }
];
